README.org --- description



Copyright (C) 2012 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>



  This file is part of bidirectional-logic-level-converter.

  bidirectional-logic-level-converter is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  bidirectional-logic-level-converter is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with bidirectional-logic-level-converter.  If not, see <http://www.gnu.org/licenses/>.



* Keywords:
  bidirectional logic level converter electronic i2c

* Description:
  convert signal form (for example) 5v -> 3v and  3v -> 5v

* Usage:

* History:
  Version 0.1 was created at 2012-02(feb)-02






* Dependences:
  
  
* Comment
